### PR TITLE
New 2898 in-progress page

### PR DESCRIPTION
**Pull request by networking-sorceress**
I have created a new page for us to show on the 2898 site while it is in progress. I would love it if this were updated to the server ASAP.

Thanks.

### CODE REVIEW

**Comment by philiparola** [comment]
Broken links throughout; add ./ and ../ to fix.

**Comment by networking-sorceress** [comment]
The broken links are because the pages don't exist. Also, put them on a server, with the pages in place, and they will work. I'm assuming it's going to be running on a server, am I wrong to assume this? Anyways, replaced the page names with hashtags to avoid this for now.

Also, using directories for each page with index files simply because it looks more professional. That won't work on a local computer. If you put them on a server it will work. I know because I reconfigured my desktop here as a Linux server. Anyways, new changes are pushed to mine, I'll submit a new pull request.

**Comment by jonah-m1** [comment]
Test it in a mamp environment first.

Let me know if you have any regarding questions.

Jonah Miller
Cell: (503)-319-1709

**Comment by networking-sorceress** [comment]
@jonah-m1 I tested it in a full Linux server at my house. Everything checks out.

**Comment by jonah-m1** [comment]
I will test on my own later when I'm free. Before being posted on production sever. 

Let me know if you have any regarding questions.

Jonah Miller
Cell: (503)-319-1709

**Comment by philiparola** [comment]
You still need to have relative directory references.  Perhaps it works on your server, but I emphasize portability.  While I would never create a directory for each file to make it 'more professional,' that was not my criticism.  The links simply did not work.

**Comment by networking-sorceress** [comment]
Portability is important, I agree. That being said, absolute directories have worked on EVERY server I have ever used or put a website on. This includes Linux servers, OSX servers, and MAMP servers. For example, this is an anchor tag on a Google Classroom page:

`<a class="oOGT6" aria-label="Back to stream" href="/u/1/c/ODkxMzQwOTYw" target="_self" jsaction="appNavigate" jsnamespace="hrNS">`

Another anchor tag, this one from giantbomb.com's navbar:

<a
 href="/new-games/">
(sorry, markdown was being dumb and making this an actual link)

It will work on everything except opening the file directly on a computer, which won't ever happen with a server-hosted website. Adding 'relative' paths becomes painful very quickly when you want, say, an importable navbar (which I plan on doing once I add a second page) or when you have large directory trees. You lose track of which directory you're going back to. The root of the website is always the directory containing the site, and that can be referenced in links with just a slash. I have never had any problems using this method, unless I'm opening them from Windows Explorer or Finder, but since it will be server-hosted that really shouldn't be a concern.

If you are still concerned about this, please let me know and tell me why beyond "I want portability" because this is portable. I'm not trying to sound rude or arrogant. I just want the website to work the best and be as readable as possible, and, based on my experience, this is the best way to do so.

**Comment by philiparola** [comment]
You are assuming two things: that the folder structure will always stay the same as it is now, and that portability only refers to servers.  You use relative links because we may add another directory between 2898 and the root, and also so people in the future have less difficulty while maintaining the website.

**Comment by jonah-m1** [comment]
It is important to have portability and be usable by all users living and artificial. That being said search engines do their job best when all files are in the dame directory and links are not complex. We want our message to be gotten out to as many people as possible. The website will not be posted until what Philip and I have requested it completed. If you need help correcting this please let us know, we both have experience with the front end and back end of these sites. 

Let me know if you have any regarding questions.

Jonah Miller
Cell: (503)-319-1709

**Comment by networking-sorceress** [comment]
I'm planning on having a modular site, that uses PHP to import a single navbar file that can be changed at any time. This one file will then be imported to every page on the site, with the current page determined by a tiny amount of javascript. This has worked well for me in the past and continues to work well for me now. It makes a much more easily maintainable website. **However**, because this navbar will be imported everywhere, **including in subdirectories**, pwd-relative paths break anywhere except site index and pages in that directory. Find me a way to do this, which by the way makes **everybody's** lives **much** easier in the long run when we want to add pages, without using root-relative paths. Then I will comply. Until then, I cannot make this requested change.

Also, ../../../../../../../index.html is a lot more complex than /. I don't really know where you got that from. That is what this will come to eventually as we add more pages that have subpages (forums, for example). Nearly every website uses root-relative paths, meaning it is what search engines will be optimized for. I don't really understand the necessity of this request, and it will take far more time to develop and push out than something else.

Also, if and when we decide to move the 2898 directory (I don't really know where we would, a /teams directory maybe?) it would take much less time with the system I have outlined than even adding one page would using your system, due to only having to edit one file rather than every file on the site.

Again, not trying to sound arrogant or rude, but I see this change hurting our web developers down the road. I'm only trying to make it as simple as possible to edit down the road. Is that not an acceptable goal?

**Comment by jonah-m1** [comment]
Let's keep the site simple for now and expand as we need it. Remember red kiss? "Keep It So Simple" it's best to for programming and debugging to have as few folders as possible and keep to older standards. Also having more then 2 programming languages on the same page starts getting buggy after a while. It uses a lot more ram on the client web browsers.

Let me know if you have any regarding questions.

Jonah Miller
Cell: (503)-319-1709

**Comment by philiparola** [comment]
This entire reason hinges on a feature which, by your own admission, does not exist yet.  So not only is it irrelevant, the code will be rewritten anyway.  Nor would this feature have any impact on the use of relative paths in the rest of the webpage code.

**Comment by philiparola** [comment]
@jonah-m1 set up a test web server, and has opened it up for you to look at.  Go to [http://team1510.dyndns.org/robotics](http://team1510.dyndns.org/robotics) and try your website out.
Then tell me what you see is wrong.
Then explain to me why you said it was working, while it clearly is not.

**Comment by philiparola** [comment]
@jonah-m1 set up a test web server, and has opened it up for you to look at.  Go to [http://team1510.dyndns.org/robotics/2898](http://team1510.dyndns.org/robotics/2898) and try your website out.
It shows that your code breaks when placed another level down.  This proves a complication in the event of restructuring, or if we put the 2898 page on a different server than 1510.  We fixed the link on the FRC icon but left the style document broken to prove this point.
It's literally a few seconds worth of work.

**Pull request merged**
